disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_filter_count
  - discouraged_optional_boolean
  - modifier_order
  - redundant_nil_coalescing

excluded:
  - .build
  - Tests/ClaudeSessionsTests/Fixtures

line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_comments: true

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 800
  error: 1000
